### ISSUE TITLE
"EXCEPTION: [Errno 2] No such file or directory" when running script

### ISSUE THREAD

**Issue by aviramartac** [um-flint/pingdom-zabbix#1]
Steps to reproduce:

1. Cloned repo into folder /etc/zabbix/zabbix_scripts in Zabbix server
2. mv pingdom-zabbix.ini.sample pingdom-zabbix.ini
3. sudo vim pingdom-zabbix.ini - added appkey, username, password and zabbix server
4. sudo python pingdom-zabbix.py

result:

A list of checks is returned in the proper format, but the very last line is "EXCEPTION: [Errno 2] No such file or directory". The data is not sent to the Zabbix host.

For testing, I tried receiving the data from Pingdom API using the following command:

`curl -u <user>@<domain>.com:<password> -H "app-key: <key>" https://api.pingdom.com/api/2.0/checks
`
Data is received correctly with no errors.

**Comment by aviramartac** [comment]
UPDATE:

I have solved this particular error by installing zabbix-sender (which I did not know was a requisite).
But now there is another issue:

I am getting "failed" on all the items, so for example:

`zabbix_sender -z 10.100.100.240 # your zabbix server -p 10051 # port the zabbix trapper listens on -s Pingdom # host to send the traps to -k pingdom.resptime # response time key[BETA CC DE something.something.com] -o 1634
EXCEPTION
returncode: 2
cmd: ['zabbix_sender', '-z', '10.100.100.240 # your zabbix server', '-p', '10051 # port the zabbix trapper listens on', '-s', 'Pingdom # host to send the traps to', '-k', 'pingdom.resptime # response time key[BETA CC DE something.something.com]', '-o', '1634']
output: info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000029"
sent: 1; skipped: 0; total: 1
`
I have enabled trappers in Zabbix conf, created a host named "Pingdom" and attached the template to it. Any ideas? or how to debug this

**Comment by mamercad** [comment]
Can you run the `zabbix_sender` command, manually, and add `-vv` to see if the output is helpful in diagnosing?

**Comment by aviramartac** [comment]
Well, I figured it out. It was my bad, I left the # descriptions in the ini file, thinking they will be ignored as comments. They weren't. 

After removing them, everything works

**Comment by mamercad** [comment]
Ah, good to hear.
